#pragma once

#include <stdio.h>
#include <stdarg.h>
#include <time.h>
#include <string.h>
#include <errno.h> 
#include <signal.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <ncurses.h>
#include <sys/wait.h>
#include <dirent.h>
#include <ctype.h>
#include <dlfcn.h>
#include <sys/mount.h>
#include <ctype.h>

#include "store/store.h"
#include "utils/command.h"
#include "utils/disk.h"
#include "utils/dependencies.h"
#include "install/progress.h"
#include "ui/ui.h"
#include "ui/modal.h"
#include "ui/interfaces.h"
#include "ui/install.h"
#include "steps/steps.h"
#include "steps/locale.h"
#include "steps/disk.h"
#include "steps/partition/table.h"
#include "steps/partition/dialogs.h"
#include "steps/partition/partition.h"
#include "steps/confirm.h"
#include "install/install.h"
#include "install/partitions.h"
#include "install/rootfs.h"
#include "install/bootloader.h"
#include "install/locale.h"
#include "install/cleanup.h"
